name: zItems
author: Traqueur_
main: fr.traqueur.items.ZItems
website: https://groupez.dev
description: Custom items
version: ${version}
api-version: 1.21
folia-supported: true
depend:
  - zMenu
libraries:
  - net.kyori:adventure-api:4.18.0
  - net.kyori:adventure-text-minimessage:4.18.0
  - net.kyori:adventure-platform-bukkit:4.3.4
  - org.reflections:reflections:0.10.2